SBA-23 As a content manager, ISBAT manage tags, so that I can create/rename/delete tags
pradeepsixer/solar-spell-build-automation pull request #3
Opened 2018-02-23 20:24 UTC by Novice052

2018-02-23 21:31 UTC, pradeepsixer requested changes

2018-02-23 21:31 UTC, pradeepsixer commented on build_automation/build_automation/urls.py
> +] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
Static URLs should be handled by Django only in Development environment. How about adding an environment variable that tells us whether it is a production or development environment?
Then, if it is a dev env, just append the static urls to the urlpatterns?

2018-02-23 21:31 UTC, pradeepsixer commented on build_automation/build_automation/urls.py
> +    path('content_management/', include('content_management.urls')),
Since the content management's views are not ready yet, how about removing this for now?

2018-02-23 21:31 UTC, pradeepsixer commented on build_automation/content_management/urls.py
> +from django.conf.urls import url, include
Since the views are not ready for this app yet, how about removing this file, or just removing the entries in urlpatterns?

2018-03-21 15:25 UTC, closed without merging

2018-03-21 15:26 UTC, Novice052 commented
Redoing.  Will create a new request.